//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("pi_ecommerceModel", "FK_game_desenvolvedor", "game_desenvolvedor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PIDashboard.game_desenvolvedor), "game", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PIDashboard.game), true)]
[assembly: EdmRelationshipAttribute("pi_ecommerceModel", "FK_game_genero", "game_genero", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PIDashboard.game_genero), "game", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PIDashboard.game), true)]
[assembly: EdmRelationshipAttribute("pi_ecommerceModel", "FK_game_plataforma", "game_plataforma", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PIDashboard.game_plataforma), "game", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PIDashboard.game), true)]
[assembly: EdmRelationshipAttribute("pi_ecommerceModel", "FK_usuario_tipo", "usuario_tipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PIDashboard.usuario_tipo), "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PIDashboard.usuario), true)]
[assembly: EdmRelationshipAttribute("pi_ecommerceModel", "FK_game_usuario", "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PIDashboard.usuario), "game", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PIDashboard.game), true)]

#endregion

namespace PIDashboard
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pi_ecommerceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pi_ecommerceEntities object using the connection string found in the 'pi_ecommerceEntities' section of the application configuration file.
        /// </summary>
        public pi_ecommerceEntities() : base("name=pi_ecommerceEntities", "pi_ecommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pi_ecommerceEntities object.
        /// </summary>
        public pi_ecommerceEntities(string connectionString) : base(connectionString, "pi_ecommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pi_ecommerceEntities object.
        /// </summary>
        public pi_ecommerceEntities(EntityConnection connection) : base(connection, "pi_ecommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<game> game
        {
            get
            {
                if ((_game == null))
                {
                    _game = base.CreateObjectSet<game>("game");
                }
                return _game;
            }
        }
        private ObjectSet<game> _game;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<game_desenvolvedor> game_desenvolvedor
        {
            get
            {
                if ((_game_desenvolvedor == null))
                {
                    _game_desenvolvedor = base.CreateObjectSet<game_desenvolvedor>("game_desenvolvedor");
                }
                return _game_desenvolvedor;
            }
        }
        private ObjectSet<game_desenvolvedor> _game_desenvolvedor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<game_genero> game_genero
        {
            get
            {
                if ((_game_genero == null))
                {
                    _game_genero = base.CreateObjectSet<game_genero>("game_genero");
                }
                return _game_genero;
            }
        }
        private ObjectSet<game_genero> _game_genero;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<game_plataforma> game_plataforma
        {
            get
            {
                if ((_game_plataforma == null))
                {
                    _game_plataforma = base.CreateObjectSet<game_plataforma>("game_plataforma");
                }
                return _game_plataforma;
            }
        }
        private ObjectSet<game_plataforma> _game_plataforma;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuario
        {
            get
            {
                if ((_usuario == null))
                {
                    _usuario = base.CreateObjectSet<usuario>("usuario");
                }
                return _usuario;
            }
        }
        private ObjectSet<usuario> _usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario_tipo> usuario_tipo
        {
            get
            {
                if ((_usuario_tipo == null))
                {
                    _usuario_tipo = base.CreateObjectSet<usuario_tipo>("usuario_tipo");
                }
                return _usuario_tipo;
            }
        }
        private ObjectSet<usuario_tipo> _usuario_tipo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the game EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogame(game game)
        {
            base.AddObject("game", game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the game_desenvolvedor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogame_desenvolvedor(game_desenvolvedor game_desenvolvedor)
        {
            base.AddObject("game_desenvolvedor", game_desenvolvedor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the game_genero EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogame_genero(game_genero game_genero)
        {
            base.AddObject("game_genero", game_genero);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the game_plataforma EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogame_plataforma(game_plataforma game_plataforma)
        {
            base.AddObject("game_plataforma", game_plataforma);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario(usuario usuario)
        {
            base.AddObject("usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario_tipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario_tipo(usuario_tipo usuario_tipo)
        {
            base.AddObject("usuario_tipo", usuario_tipo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pi_ecommerceModel", Name="game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new game object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        /// <param name="lancamento">Initial value of the Lancamento property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="imagemURL">Initial value of the ImagemURL property.</param>
        /// <param name="iDDesenvolvedor">Initial value of the IDDesenvolvedor property.</param>
        /// <param name="iDGenero">Initial value of the IDGenero property.</param>
        /// <param name="iDPlataforma">Initial value of the IDPlataforma property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        public static game Creategame(global::System.Int32 id, global::System.String titulo, global::System.Decimal preco, global::System.DateTime lancamento, global::System.String descricao, global::System.String imagemURL, global::System.Int32 iDDesenvolvedor, global::System.Int32 iDGenero, global::System.Int32 iDPlataforma, global::System.Int32 iDUsuario)
        {
            game game = new game();
            game.ID = id;
            game.Titulo = titulo;
            game.Preco = preco;
            game.Lancamento = lancamento;
            game.Descricao = descricao;
            game.ImagemURL = imagemURL;
            game.IDDesenvolvedor = iDDesenvolvedor;
            game.IDGenero = iDGenero;
            game.IDPlataforma = iDPlataforma;
            game.IDUsuario = iDUsuario;
            return game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Lancamento
        {
            get
            {
                return _Lancamento;
            }
            set
            {
                OnLancamentoChanging(value);
                ReportPropertyChanging("Lancamento");
                _Lancamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lancamento");
                OnLancamentoChanged();
            }
        }
        private global::System.DateTime _Lancamento;
        partial void OnLancamentoChanging(global::System.DateTime value);
        partial void OnLancamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImagemURL
        {
            get
            {
                return _ImagemURL;
            }
            set
            {
                OnImagemURLChanging(value);
                ReportPropertyChanging("ImagemURL");
                _ImagemURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImagemURL");
                OnImagemURLChanged();
            }
        }
        private global::System.String _ImagemURL;
        partial void OnImagemURLChanging(global::System.String value);
        partial void OnImagemURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDDesenvolvedor
        {
            get
            {
                return _IDDesenvolvedor;
            }
            set
            {
                if (_IDDesenvolvedor != value)
                {
                    OnIDDesenvolvedorChanging(value);
                    ReportPropertyChanging("IDDesenvolvedor");
                    _IDDesenvolvedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDDesenvolvedor");
                    OnIDDesenvolvedorChanged();
                }
            }
        }
        private global::System.Int32 _IDDesenvolvedor;
        partial void OnIDDesenvolvedorChanging(global::System.Int32 value);
        partial void OnIDDesenvolvedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDGenero
        {
            get
            {
                return _IDGenero;
            }
            set
            {
                if (_IDGenero != value)
                {
                    OnIDGeneroChanging(value);
                    ReportPropertyChanging("IDGenero");
                    _IDGenero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDGenero");
                    OnIDGeneroChanged();
                }
            }
        }
        private global::System.Int32 _IDGenero;
        partial void OnIDGeneroChanging(global::System.Int32 value);
        partial void OnIDGeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPlataforma
        {
            get
            {
                return _IDPlataforma;
            }
            set
            {
                if (_IDPlataforma != value)
                {
                    OnIDPlataformaChanging(value);
                    ReportPropertyChanging("IDPlataforma");
                    _IDPlataforma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPlataforma");
                    OnIDPlataformaChanged();
                }
            }
        }
        private global::System.Int32 _IDPlataforma;
        partial void OnIDPlataformaChanging(global::System.Int32 value);
        partial void OnIDPlataformaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_desenvolvedor", "game_desenvolvedor")]
        public game_desenvolvedor game_desenvolvedor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_desenvolvedor>("pi_ecommerceModel.FK_game_desenvolvedor", "game_desenvolvedor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_desenvolvedor>("pi_ecommerceModel.FK_game_desenvolvedor", "game_desenvolvedor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<game_desenvolvedor> game_desenvolvedorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_desenvolvedor>("pi_ecommerceModel.FK_game_desenvolvedor", "game_desenvolvedor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<game_desenvolvedor>("pi_ecommerceModel.FK_game_desenvolvedor", "game_desenvolvedor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_genero", "game_genero")]
        public game_genero game_genero
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_genero>("pi_ecommerceModel.FK_game_genero", "game_genero").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_genero>("pi_ecommerceModel.FK_game_genero", "game_genero").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<game_genero> game_generoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_genero>("pi_ecommerceModel.FK_game_genero", "game_genero");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<game_genero>("pi_ecommerceModel.FK_game_genero", "game_genero", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_plataforma", "game_plataforma")]
        public game_plataforma game_plataforma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_plataforma>("pi_ecommerceModel.FK_game_plataforma", "game_plataforma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_plataforma>("pi_ecommerceModel.FK_game_plataforma", "game_plataforma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<game_plataforma> game_plataformaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<game_plataforma>("pi_ecommerceModel.FK_game_plataforma", "game_plataforma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<game_plataforma>("pi_ecommerceModel.FK_game_plataforma", "game_plataforma", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_usuario", "usuario")]
        public usuario usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("pi_ecommerceModel.FK_game_usuario", "usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("pi_ecommerceModel.FK_game_usuario", "usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario> usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("pi_ecommerceModel.FK_game_usuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario>("pi_ecommerceModel.FK_game_usuario", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pi_ecommerceModel", Name="game_desenvolvedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class game_desenvolvedor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new game_desenvolvedor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static game_desenvolvedor Creategame_desenvolvedor(global::System.Int32 id, global::System.String nome)
        {
            game_desenvolvedor game_desenvolvedor = new game_desenvolvedor();
            game_desenvolvedor.ID = id;
            game_desenvolvedor.Nome = nome;
            return game_desenvolvedor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_desenvolvedor", "game")]
        public EntityCollection<game> game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<game>("pi_ecommerceModel.FK_game_desenvolvedor", "game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<game>("pi_ecommerceModel.FK_game_desenvolvedor", "game", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pi_ecommerceModel", Name="game_genero")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class game_genero : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new game_genero object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static game_genero Creategame_genero(global::System.Int32 id, global::System.String descricao)
        {
            game_genero game_genero = new game_genero();
            game_genero.ID = id;
            game_genero.Descricao = descricao;
            return game_genero;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_genero", "game")]
        public EntityCollection<game> game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<game>("pi_ecommerceModel.FK_game_genero", "game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<game>("pi_ecommerceModel.FK_game_genero", "game", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pi_ecommerceModel", Name="game_plataforma")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class game_plataforma : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new game_plataforma object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static game_plataforma Creategame_plataforma(global::System.Int32 id, global::System.String nome)
        {
            game_plataforma game_plataforma = new game_plataforma();
            game_plataforma.ID = id;
            game_plataforma.Nome = nome;
            return game_plataforma;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_plataforma", "game")]
        public EntityCollection<game> game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<game>("pi_ecommerceModel.FK_game_plataforma", "game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<game>("pi_ecommerceModel.FK_game_plataforma", "game", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pi_ecommerceModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static usuario Createusuario(global::System.Int32 id, global::System.String username, global::System.String nome, global::System.String senha, global::System.Int32 tipo)
        {
            usuario usuario = new usuario();
            usuario.ID = id;
            usuario.Username = username;
            usuario.Nome = nome;
            usuario.Senha = senha;
            usuario.Tipo = tipo;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.Int32 _Tipo;
        partial void OnTipoChanging(global::System.Int32 value);
        partial void OnTipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_usuario_tipo", "usuario_tipo")]
        public usuario_tipo usuario_tipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario_tipo>("pi_ecommerceModel.FK_usuario_tipo", "usuario_tipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario_tipo>("pi_ecommerceModel.FK_usuario_tipo", "usuario_tipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario_tipo> usuario_tipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario_tipo>("pi_ecommerceModel.FK_usuario_tipo", "usuario_tipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario_tipo>("pi_ecommerceModel.FK_usuario_tipo", "usuario_tipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_game_usuario", "game")]
        public EntityCollection<game> game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<game>("pi_ecommerceModel.FK_game_usuario", "game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<game>("pi_ecommerceModel.FK_game_usuario", "game", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pi_ecommerceModel", Name="usuario_tipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario_tipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario_tipo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static usuario_tipo Createusuario_tipo(global::System.Int32 id, global::System.String descricao)
        {
            usuario_tipo usuario_tipo = new usuario_tipo();
            usuario_tipo.ID = id;
            usuario_tipo.Descricao = descricao;
            return usuario_tipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pi_ecommerceModel", "FK_usuario_tipo", "usuario")]
        public EntityCollection<usuario> usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("pi_ecommerceModel.FK_usuario_tipo", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("pi_ecommerceModel.FK_usuario_tipo", "usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
